#!/usr/bin/perl

# Purpose:  Read linux sensors, report to graphite

use strict;
use Getopt::Long;
use vars qw (%Config);
use Time::Local;
use POSIX 'strftime';
use Sys::Hostname;

unless(GetOptions(
    "debug" => \$Config{debug},
    "prefix=s" => \$Config{prefix},
    "graphite-server=s" => \$Config{graphite},
       )) {
    print STDERR "Invalid usage\n";
    exit 1;
}


&main;

sub main {
    open(my $sensors, "sensors 2>/dev/null |") || die("Failed to run sensors: $!");

    my $now = strftime("%s", localtime);

    unless(defined $Config{prefix}) {
	$Config{prefix} = "system." . hostname . ".sensors" 
    }

    my $graphite;
    if($Config{graphite}) {
        open($graphite, "|nc $Config{graphite} 2003") || die("Failed to netcat to $Config{graphite}: $!");
	select $graphite; 
    }

    my $adapter;
    my $module;
    my $errors;

    while(<$sensors>) {
	chop;
	if(/^[a-zA-Z0-9-]+$/) {
	    $module = $&;
	}
	if(/Adapter: (.*)/) {
	    $adapter = $1;
	}

	if(/ERROR:/) {
	    $errors++;
	    next;
	}

	if(/\s*([^:]+)+:\s*\+?([\d\.]+)/) {
	    my $key = $1;
	    my $value = $2;

	    &write("$module.$key.level", $value, $now);
	}
    }

    close $graphite if $graphite;
}


sub write {
    my $key = shift;
    my $value = shift;
    my $date = shift;

    my $metric = "$Config{prefix}.$key";

    $metric =~ s/[^a-zA-Z0-9_\.]/_/g;

    print "$metric $value $date\n";
}
