#!/bin/bash

dir=/var/lib/graphite/probes
logproc=/var/lib/graphite/logs

while [ -n "$*" ] ; do
  case $1 in 
      -prefix) prefix="$2"; shift;;
      -graphite) graphite="$2"; shift;;
      -sleep) sleep="$2"; shift;;
      -*) echo "Unknown option $1"; exit 1;;
      *) echxo "Unknown argument $1"; exit 2;;
  esac    
  shift
done

if [ -z "$prefix" ] ; then
    prefix="system.`hostname`"
fi

if [ -z "$graphite" ] ; then
    graphite="graphite"
fi

# splay the load on the graphite server
test -n "$sleep" && sleep $sleep

for probe in $dir/graphite-probe*; do
    if [ -x $probe ] ; then
	if [ -f $probe.args ] ;then
	    $probe  -prefix $prefix -graphite $graphite `cat $probe.args`
	else
	    $probe  -prefix $prefix -graphite $graphite
	fi
    fi
done

if [ -d $logproc ] ; then
    for args in $logproc/*.glog; do
	$logproc/graphite-log -graphite $graphite `cat $args`
    done
fi